exec-once = waybar
exec-once = hyprpaper
exec-once = nm-applet --indicator
exec-once = hyprlock

# Start Polkit agent (the path for polkit_gnome on NixOS)
exec-once = /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1

# Start udiskie for auto-mounting
exec-once = udiskie &