exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Start SwayOSD once Hyprland is ready
exec-once = systemctl --user restart swayosd.service

exec-once = waybar
exec-once = ~/.config/hypr/slideshow.sh --with-loop
exec-once = nm-applet --indicator
exec-once = hyprlock
exec-once = easyeffects -w
exec-once = ~/.config/hypr/layout_osd.sh

# Start Polkit agent (the path for polkit_gnome on NixOS)
exec-once = /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1

# Start udiskie for auto-mounting
exec-once = udiskie &