# Window Layout configurations

general {
    layout = dwindle
}

dwindle {
    pseudotile = yes # master switch for pseudotiling
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
}