# --- Picture-in-Picture Rules ---
# Firefox
windowrule {
  name = windowrule-1
  float = on
  pin = on
  size = (monitor_w*0.3) (monitor_h*0.3)
  move = ((monitor_w*0.69)) ((monitor_h*0.69))
  match:title = ^(Picture-in-Picture|Incrustation vidéo)$
}


# MPV
windowrule {
  name = windowrule-2
  float = on
  pin = on
  keep_aspect_ratio = on
  size = (monitor_w*0.3) (monitor_h*0.3)
  move = ((monitor_w*0.69)) ((monitor_h*0.69))
  no_initial_focus = on
  match:class = ^(mpv)$
}




# Allow pinned (PiP) windows to go fullscreen
binds {
    allow_pin_fullscreen = true
}