# --- Picture-in-Picture Rules ---
# Rule for Firefox
windowrulev2 = float, title:^(Picture-in-Picture|Incrustation vidéo)$
windowrulev2 = pin, title:^(Picture-in-Picture|Incrustation vidéo)$
windowrulev2 = size 30% 30%, title:^(Picture-in-Picture|Incrustation vidéo)$
windowrulev2 = move 69% 69%, title:^(Picture-in-Picture|Incrustation vidéo)$

# Allow pinned (PiP) windows to go fullscreen
binds {
    allow_pin_fullscreen = true
}