# --- Picture-in-Picture Rules ---
# Firefox
windowrulev2 = float, title:^(Picture-in-Picture|Incrustation vidéo)$
windowrulev2 = pin, title:^(Picture-in-Picture|Incrustation vidéo)$
windowrulev2 = size 30% 30%, title:^(Picture-in-Picture|Incrustation vidéo)$
windowrulev2 = move 69% 69%, title:^(Picture-in-Picture|Incrustation vidéo)$

# MPV
windowrulev2 = float, class:^(mpv)$
windowrulev2 = pin, class:^(mpv)$
windowrulev2 = keepaspectratio, class:^(mpv)$
windowrulev2 = size 30% 30%, class:^(mpv)$
windowrulev2 = move 69% 69%, class:^(mpv)$
windowrulev2 = noinitialfocus, class:^(mpv)$



# Allow pinned (PiP) windows to go fullscreen
binds {
    allow_pin_fullscreen = true
}