# Monitor Configuration
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,1

# Source modular config files
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/ui.conf
source = ~/.config/hypr/conf/keybinds.conf