@define-color primary {{colors.primary.default.hex}};
@define-color primary-container {{colors.primary_container.default.hex}};
@define-color background {{colors.background.default.hex}};
@define-color text {{colors.on_background.default.hex}};
@define-color accent {{colors.tertiary.default.hex}};